name: Trigger Central Semgrep Scan
#test case
on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send dispatch to central repo
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.GH_PAT }}" \
            https://api.github.com/repos/Rohitchhimpa01/Semgrep-Scanning/dispatches \
            -d '{"event_type":"semgrep_scan","client_payload":{"repo":"${{ github.repository }}"}}'
